---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    #Runner where we want to run our job on
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
      #provided actions that help you execute particular jobs. 
      #Dockercontainer or docker configuration that sets up to perform a certain task
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
      #Need to access the code and make available the code in this step
        uses: actions/checkout@v2
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py test"    
      - name: Lint
      #Docker compose is preinstalled in the ubuntu 
        run: docker compose run --rm app sh -c "flake8"     
